openapi: 3.0.0
info:
  title: 'Employee API'
  description: 'Project for MySql sample database'
  contact:
    name: me42th
  version: '1.0'
servers:
  -
    url: 'http://localhost:8000'
    description: 'Local server'
paths:
  /api/employee:
    get:
      operationId: aec9115c2e1b82bd5139f3ba90d8cd76
      responses:
        '200':
          description: 'An example endpoint'
tags:
  -
    name: employee
    description: 'Employee related operations'
